### ISSUE TITLE
pyds9 import error 

### ISSUE THREAD

**Issue by johnnygreco** [astroconda/astroconda#15]
Hello, 

pyds9 fails to import on a freshly installed astroconda on both OS X El Capitan and RHEL 6.8 (see below).  Everything works if I change xpa.so  to  _xpa.so in the site-packages directory. 

Thanks, 
Johnny

``` python
>>> import pyds9
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/u/jgreco/anaconda2/envs/astroconda/lib/python2.7/site-packages/pyds9.py", line 754, in <module>
ds9_xpans()
File "/u/jgreco/anaconda2/envs/astroconda/lib/python2.7/site-packages/pyds9.py", line 193, in ds9_xpans
 if xpa.xpaaccess(b"xpans", None, 1) is None:
AttributeError: 'module' object has no attribute 'xpaaccess'
```

**Comment by jhunkeler** [comment]
Hi @johnnygreco 

Thanks for letting us know about this.

I am see this behavior only if `pyds9` is installed via the `stsci` metapackage. If I install it directly into its own environment the module behaves normally.

## Standalone environment test

```
jhunk@makeitso:~% conda create -n pyds9test python=2.7 pyds9
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/jhunk/miniconda3/envs/pyds9test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ds9-7.4                    |                0        11.3 MB  http://ssb.stsci.edu/astroconda
    mkl-11.3.3                 |                0       101.4 MB
    xpa-2.1.17                 |                0         600 KB  http://ssb.stsci.edu/astroconda
    python-2.7.12              |                1         9.5 MB
    numpy-1.11.1               |           py27_0         3.1 MB
    setuptools-23.0.0          |           py27_0         456 KB
    six-1.10.0                 |           py27_0          16 KB
    wheel-0.29.0               |           py27_0          81 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    pyds9-1.8.1                |      np111py27_0         120 KB  http://ssb.stsci.edu/astroconda
    ------------------------------------------------------------
                                           Total:       128.0 MB

The following NEW packages will be INSTALLED:

    ds9:        7.4-0             http://ssb.stsci.edu/astroconda
    mkl:        11.3.3-0
    numpy:      1.11.1-py27_0
    openssl:    1.0.2h-1
    pip:        8.1.2-py27_0
    pyds9:      1.8.1-np111py27_0 http://ssb.stsci.edu/astroconda
    python:     2.7.12-1
    readline:   6.2-2
    setuptools: 23.0.0-py27_0
    six:        1.10.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    xpa:        2.1.17-0          http://ssb.stsci.edu/astroconda
    zlib:       1.2.8-3

Proceed ([y]/n)? y

Fetching packages ...
[omitted progress bars...]

#
# To activate this environment, use:
# $ source activate pyds9test
#
# To deactivate this environment, use:
# $ source deactivate
#
```

## Testing

```
jhunk@makeitso:~% source activate pyds9test
(pyds9test) jhunk@makeitso:~% ds9 &
(pyds9test) jhunk@makeitso:~% python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyds9
>>>
```

**Comment by johnnygreco** [comment]
Good to know. Thanks for the quick response @jhunkeler!

**Comment by jhunkeler** [comment]
https://github.com/ericmandel/pyds9/pull/39

@jonnygreco I've issued a PR to see if we can get this resolved upstream. I haven't been able to determine the exact cause of this, but I feel like `conda-build` handles this package incorrectly when adding it to the `stsci` metapackage. 

Building 1.8.x from source works perfectly fine outside of conda, but this doesn't help us much. So ultimately I'd prefer to use the `libxpa.so` provided by AstroConda's `xpa` package, rather than the one `pyds9` provides at compile-time.

If this PR is accepted I'll distribute whatever is on `pyds9`'s master branch until a proper release (i.e. 1.9.x) becomes available. However, if this PR is not accepted I'll try to dig deeper into the issue.

**Comment by jmccormac01** [comment]
Hi guys,
I am suffering from the same issue. Is there likely to be a fix for this anytime soon?

Cheers
James

**Comment by mrutkowski-su** [comment]
@jmccormac01 were you ever able to find a workaround for this by chance?  Has anyone contacted ST regarding this; I don't see anything in the FAQs there for example, but I don't want to duplicate a request someone has already made to them if possible.

**Comment by jhunkeler** [comment]
@jmccormac01 No unfortunately. The only viable workaround turned out to be including an unreleased version of `pyds9` into AstroConda. A new build should appear in the repository at ~0700 EST.

Updating to 1.9.0.dev-XX should require nothing more than:
```
conda update pyds9
```

Please let me know if you encounter any problems with this new build.

cc @johnnygreco
