### ISSUE TITLE
zsh issues with iraf

### ISSUE THREAD

**Issue by wkerzendorf** [astroconda/astroconda#4]
First of all: Great work @jhunkeler !!!

I'm having some zsh issues with iraf: somehow the variable `$iraf` gets set to 

```
bin
conda-meta
etc
gcc
imports
include
iraf
lib
man
mkspecs
phrasebooks
plugins
python.app
q3porting.xml
share
ssl
tests
translations
variants
/Users/wkerzend/anaconda3/envs/sn2011fe/iraf/
```
instead to `/Users/wkerzend/anaconda3/envs/sn2011fe/iraf/` no idea why.

**Comment by jhunkeler** [comment]
Thanks @wkerzendorf ;)

ZSH is my primary shell as well, however, it seems I am unable to reproduce this behavior on my end. The `iraf` recipe's [build.sh](https://github.com/astroconda/astroconda-contrib/blob/master/iraf/build.sh#L109) emits a shell script `$CONDA_ENV_PATH/etc/conda/activate.d/iraf.sh` that gets sourced when you call `source activate [envname]`.

So we can compare notes, I executed this script in debug mode instead of sourcing it to show you what would end up in my environment at after `source activate`:

```bash
(iraf27)jhunk@makeitso:~% sh -x $CONDA_ENV_PATH/etc/conda/activate.d/iraf.sh
+ export IRAFARCH=macosx
+ IRAFARCH=macosx
+ export iraf=/Users/jhunk/miniconda3/envs/iraf27/iraf/
+ iraf=/Users/jhunk/miniconda3/envs/iraf27/iraf/
+ export MACH=macosx
+ MACH=macosx
+ export hostid=unix
+ hostid=unix
+ export host=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix/
+ host=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix/
+ export hbin=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx/
+ hbin=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx/
+ export IMTOOLRC=/Users/jhunk/miniconda3/envs/iraf27/iraf//dev/imtoolrc
+ IMTOOLRC=/Users/jhunk/miniconda3/envs/iraf27/iraf//dev/imtoolrc
+ export tmp=/tmp/
+ tmp=/tmp/
+ export CC=gcc
+ CC=gcc
+ export F2C=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx//f2c.e
+ F2C=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx//f2c.e
+ export F77=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx//f77.sh
+ F77=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix//bin.macosx//f77.sh
+ export RANLIB=ranlib
+ RANLIB=ranlib
+ case macosx in
+ export 'HSI_CF=-O -DMACOSX -w -Wunused -arch i386 -m32 -mmacosx-version-min=10.4'
+ HSI_CF='-O -DMACOSX -w -Wunused -arch i386 -m32 -mmacosx-version-min=10.4'
+ export 'HSI_XF=-Inolibc -/DMACOSX -w -/Wunused -/m32 -/arch -//i386 -/mmacosx-version-min=10.4'
+ HSI_XF='-Inolibc -/DMACOSX -w -/Wunused -/m32 -/arch -//i386 -/mmacosx-version-min=10.4'
+ export 'HSI_FF=-O -arch i386 -m32 -DBLD_KERNEL -mmacosx-version-min=10.4'
+ HSI_FF='-O -arch i386 -m32 -DBLD_KERNEL -mmacosx-version-min=10.4'
+ export 'HSI_LF=-arch i386 -m32 -mmacosx-version-min=10.4'
+ HSI_LF='-arch i386 -m32 -mmacosx-version-min=10.4'
+ export HSI_F77LIBS=
+ HSI_F77LIBS=
+ export 'HSI_LIBS=/Users/jhunk/miniconda3/envs/iraf27/iraf//unix/hlib/libboot.a /Users/jhunk/miniconda3/envs/iraf27/iraf//lib/libsys.a /Users/jhunk/miniconda3/envs/iraf27/iraf//lib/libvops.a /Users/jhunk/miniconda3/envs/iraf27/iraf//unix/hlib/libos.a'
+ HSI_LIBS='/Users/jhunk/miniconda3/envs/iraf27/iraf//unix/hlib/libboot.a /Users/jhunk/miniconda3/envs/iraf27/iraf//lib/libsys.a /Users/jhunk/miniconda3/envs/iraf27/iraf//lib/libvops.a /Users/jhunk/miniconda3/envs/iraf27/iraf//unix/hlib/libos.a'
+ export HSI_OSLIBS=
+ HSI_OSLIBS=
+ export UR_BITS=64
+ UR_BITS=64
+ export UR_CPU=x86_64
+ UR_CPU=x86_64
+ export UR_DIR=/Users/jhunk/miniconda3/envs/iraf27
+ UR_DIR=/Users/jhunk/miniconda3/envs/iraf27
+ export UR_VARIANT=common
+ UR_VARIANT=common
+ export UR_OS=osx
+ UR_OS=osx
+ export UR_TMP=/tmp
+ UR_TMP=/tmp
+ export UR_DIR_PKG=/Users/jhunk/miniconda3/envs/iraf27/variants/common/
+ UR_DIR_PKG=/Users/jhunk/miniconda3/envs/iraf27/variants/common/
```

And a quick run-through of my IRAF environment:

```bash
# Activating my python2.7-based iraf installation
(iraf27)jhunk@makeitso:~% source activate iraf27
discarding /Users/jhunk/miniconda3/envs/iraf27/bin from PATH
prepending /Users/jhunk/miniconda3/envs/iraf27/bin to PATH

# Verifying where the package came from
(iraf27)jhunk@makeitso:~% conda list iraf
# packages in environment at /Users/jhunk/miniconda3/envs/iraf27:
#
iraf                      2.16.1                        0    http://ssb.stsci.edu/astroconda/osx-64/iraf-2.16.1-0.tar.bz2

# Verifying the enviornment path
(iraf27)jhunk@makeitso:~% echo $CONDA_ENV_PATH
/Users/jhunk/miniconda3/envs/iraf27

# Verify $iraf is derived from $CONDA_ENV_PATH
(iraf27)jhunk@makeitso:~% echo $iraf
/Users/jhunk/miniconda3/envs/iraf27/iraf/
```

I hope this helps track down where the issue is coming from. Let me know if you need anything!

**Comment by dafh** [comment]
Hi jhunkeler! I'm new in miniconda and recently I have tried to use tcsh and 'activate' (see https://github.com/conda/conda/pull/3175); I'm able to 'enter' to iraf27 env, but this iraf.sh doesn't work in my case (it is written for sh/bash I guess), for example, I don't have IRAFARCH setted up, nor CONDA_ENV_PATH. Can you tell me what changes do I need to do in order to make this work?

**Comment by pllim** [comment]
Could you please provide the exact commands you use and the full error messages?

**Comment by dafh** [comment]
After following the link above (I have that version of 'conda), I do:

source \`which \activate\` iraf27 
(iraf27) [dafh@dhcp121-217 ~]$ mkiraf
Initialize uparm? (y|n): y
-- initializing uparm
Terminal types: xgterm,xterm,gterm,vt640,vt100,etc.
Enter terminal type [default xterm-256color]: xgterm
/home/dafh/miniconda2/envs/iraf27/bin/mkiraf: line 126: /unix/hlib/login.cl: No such file or directory
A new LOGIN.CL file has been created in the current directory.
You may wish to review and edit this file to change the defaults.
You may also add additional customizations to loginuser.cl
(iraf27) [dafh@dhcp121-217 ~]$ xgterm &

*On the xgterm shell*

dafh@dhcp121-217 ~]$ cl
IRAFARCH not set

I don't know where do I call this 'iraf.sh' script, but I'm gonna try now changing to sh/bash and see if this works properly

**Comment by dafh** [comment]
Confirmation: It works properly with bash shell (I can enter to IRAF), but I need a workaround with tcsh; my first impression is that at the moment of 'source \`which \activate`  iraf27' * (edit), tcsh doesn't do the job with iraf.sh; that's why I don't set the environments variables such as $iraf, $IRAFARCH, etc, and cl doesn't work.

**Comment by dafh** [comment]
/home/dafh/miniconda2/envs/iraf27/bin/mkiraf: line 126: /unix/hlib/login.cl: No such file or directory

That also would be explained because $iraf isn't setted up (  line 126 of mkiraf: sed -f _sed < $iraf/unix/hlib/login.cl > login.cl   )

**Comment by dafh** [comment]
Question; how/when it is setted up the variable "CONDA_PREFIX"?

**Comment by jhunkeler** [comment]
@dafh Conda itself does not support the use C-Shell, so that is why it is not working for you. When using BASH the `$CONDA_PREFIX/etc/conda/activate.d/iraf.sh` activation script is sourced by `conda-env`'s control scripts when you execute `source activate <env_name>`.

You may only use BASH or ZSH with if you intend to use `conda create ...` and `source activate`.

Note: `$CONDA_ENV_PATH` was deprecated by Continuum a little while ago. The variable is now called `$CONDA_PREFIX`

**Comment by dborncamp** [comment]
The reason that you can only use bash or zsh with conda is in the activate and deactivate programs that conda uses. Within activate, the first few lines run a check on the environment because it calls a few things that are not in other environments so it is restricted to bash or zsh. From a bash terminal:

    bash 2% head -13 `which activate`

Produces:

    #!/bin/bash
    
    # Determine the directory containing this script
    if [[ -n $BASH_VERSION ]]; then
        _SCRIPT_LOCATION=${BASH_SOURCE[0]}
    elif [[ -n $ZSH_VERSION ]]; then
        _SCRIPT_LOCATION=${funcstack[1]}
    else
        echo "Only bash and zsh are supported"
        return 1
    fi`

Hope that helps a little bit (More info: http://stackoverflow.com/questions/35776858/installing-conda-using-a-non-bash-shell )
