### ISSUE TITLE
miniconda3.x confusion

### ISSUE THREAD

**Issue by justincely** [astroconda/astroconda#46]
A recent user was confused by the instructions saying "obtain miniconda3" when the linked page refers to python 3.5.  The confusion was whether 3.5 will work as well as 3.  The filenames are miniconda3 and miniconda2, but that isn't seen unless you hover over the page. 

The page, at the very top, does say a few times that any of the distributions will work, but maybe there's still something to think about here.  Perhaps saying 3.x somewhere instead of 3, or highlighting that the minor version doesn't matter? 

Putting this here for tracking anyway.

**Comment by jhunkeler** [comment]
- Miniconda3 implies Python 3.x
- Miniconda2 implies Python 2.7

It's stated in our documentation, Continuum's documentation, and on the download page for Miniconda itself (and even Anaconda's download page for that matter).

Our documentation:
> This documentation targets **Miniconda3 (i.e. Python 3)**, but the installation **instructions work equally well with any of the Miniconda distributions**.
> Installing **Miniconda3 will not prevent you from using Python 2**.
conda allows you to deploy multiple independent Python environments, at-will, under a single Miniconda installation. You may have trouble following along with this guide if you choose to install Miniconda2.

From Miniconda's download page:
> There are two variants of the installer: **Miniconda is Python 2 based** and **Miniconda3 is Python 3 based**. Note that the choice of which Miniconda is installed only affects the root environment. **Regardless of which version of Miniconda you install, you can still install both Python 2.x and Python 3.x environments.**

From Anaconda's download page:
> Which version should I download and install?
With Anaconda **you can run multiple versions of Python in isolated environments**, so **choose the download with the Python version that you use more often**, as **that will be your default Python version**.

From Anaconda's documentation:
> Does Anaconda include Python 2 or Python 3?
**Anaconda2 includes Python 2.7** and **Anaconda3 includes Python 3.6**. However, **it doesn’t matter** which one you download, because you can create **new environments** that **include any version of Python packaged with conda**. See “Managing Python with conda”.

From "Managing Python with conda":
> Create Python 2 or 3 environments
**Anaconda supports Python 2.7, 3.4, and 3.5**. The **default is Python 2.7 or 3.5, depending on which installer you used**. If the installer you used is Anaconda or Miniconda, the default is 2.7. If the installer you used is Anaconda3 or Miniconda3, the default is 3.5.


The distinction is clear enough. I'm not sure what else needs to be done.

**Comment by pllim** [comment]
Would it help to add a photo of Mini-Me next to Miniconda doc? Probably not, but it will be fun!

**Comment by jhunkeler** [comment]
Fixed by #48
