### ISSUE TITLE
conda env with IRAF not working on RHEL6 64-bit

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#9]
I followed the instructions below to create an environment with IRAF, where `envname` is replaced with `ssbx`:

```
$ conda create -n envname python=2.7 iraf pyraf stsci
```

I got it to work briefly last week. But then it stopped working for no apparent reason. So, I wiped that enviroment and recreated it from scratch. Now, it just straight up does not work anymore.  After some investigation, it looks like `$iraf` is messed up:

```
$ echo $iraf
~/anaconda/envs/ssbx: bin/ conda-meta/ etc/ include/ iraf/ lib/ man/ share/ ssl/ var/ variants/ ~/anaconda/envs/ssbx/iraf/
```

So, I manually added this line at the top of `~/anaconda/envs/ssbx/iraf/unix/hlib/cl.sh` (after the comment lines):

```
iraf=$HOME/anaconda/envs/ssbx/iraf
```

After that, I tried running `cl` again and get this error instead:

```
~/anaconda/envs/ssbx/iraf/bin.linux/ecl.e: error while loading shared libraries: libncurses.so.5: wrong ELF class: ELFCLASS64
```

I am not sure what is going on here. I am using STScI RHEL6 64-bit machine, so I do not have `root` access to change any of the underlying libraries. How to fix this, @jhunkeler ?

**Comment by jhunkeler** [comment]
Create a script called `blackhole_env.sh`:

```bash
#!/bin/bash
HOME=/home/lim
[[ "$USER" != "" ]] && exec -c $0
export HOME=$NEW_HOME
export TERM=xterm
source /etc/profile
export PATH=$HOME/anaconda/bin:$PATH
```

This will completely nuke your environment in memory reset it to a basic system shell. Because we're sourcing `/etc/profile` it might still source `~/.bash_profile` or `~/.profile` in your home directory, so move them out of the way before running the script.

Run `sh blackhole_env.sh`

After you've entered the blackhole environment `source activate ssbx`. Now take a look at `printenv`. You shouldn't see `$ echo $iraf
~/anaconda/envs/ssbx: bin/ conda-meta/ etc/ include/ iraf/ lib/ man/ share/ ssl/ var/ variants/ ~/anaconda/envs/ssbx/iraf/` output anymore.

It should return `~/anaconda/envs/ssbx/iraf/`.

If you're still seeing this, then I have feeling something went wrong with your conda environment internally. Either a botched record in `~/.conda/environments.txt`, or something else (I'm not sure we'll have to look at it together). I do see a random `:` (colon) in the output, so make sure there's no colon at the end of the string in the `environments.txt` file. Conda can't seem to find the bin directory associated with your environment, it's just spitting out garbage and putting it into your path.

If you stop seeing this after entering the blackhole environment, then something in your general shell environment is causing this. We'll have to investigate this in either case, I just wanted to try to narrow down to the cause.

**Comment by jhunkeler** [comment]
As for the ncurses library, we need to have IT install ncurses-libs.i686 on the server(s). They are supposed to be included during the build.

**Comment by pllim** [comment]
I am hesistant to "nuke" my bash stuff because I already have some other stuff set up there that works. So I ended up using the VM for IRAF. Closing this.

**Comment by jhunkeler** [comment]
> This will completely nuke your environment in memory reset it to a basic system shell.

**Rephrased:**

This non-destructive script will drop you into a basic bash shell and will allow us to troubleshoot the problem.

**Comment by pllim** [comment]
Okay, fine, fine. I'll get to it when I get a chance. :wink:

**Comment by pllim** [comment]
So, I gave it a try but needed the following changes:

1. In your script, first line, I had to change `HOME=...` to `NEW_HOME=...`.
2. Then in bash, I have to `source blackhole_env.sh` (not `sh`) *twice* to pick up Anaconda in my `PATH`.

After that, indeed `iraf` is properly set to `/home/lim/anaconda/envs/ssbx/iraf/`. But I still get the following error:

```
(ssbx)bash-4.1$ cd ~/iraf
(ssbx)bash-4.1$ cl
/home/lim/anaconda/envs/ssbx/iraf//bin.linux/ecl.e: error while loading shared libraries:
libncurses.so.5: cannot open shared object file: No such file or directory
```

In case you are curious, my `~/.conda/environments.txt` looked like this (I have since deleted the duplicate lines):

```
/home/lim/anaconda/envs/py3k
/home/lim/anaconda/envs/py3k
/home/lim/anaconda/envs/ssbx
/home/lim/anaconda/envs/ssbx
```

**Comment by pllim** [comment]
Note: The above result does not matter whether I have `.bash_profile` and `.profile` removed or not.

**Comment by pllim** [comment]
I found out why `$iraf` is messed up without `blackhole_env.sh`!!! So, for whatever reason, how `$iraf` is set depends on the `cd` command?! Because I reprogrammed my `cd` command in `~/.bash.myalias`:

```
function cd {
    old=$PWD && builtin cd "$@" && echo $PWD":" && ls
}
```

When that is commented, `$iraf` is correct. Huh?!! ¯\_(ツ)_/¯

But regardless, I am still getting missing `libcurses.so.5` error.
